"""initial schema

Revision ID: 5f34b774b7a4
Revises: 
Create Date: 2026-09-16 08:26:27.256390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5f34b774b7a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('type', sa.Enum('DIRECT', 'GROUP', name='conversationtype', native_enum=False, length=16), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('direct_key', sa.String(length=65), nullable=True),
    sa.Column('members_can_add', sa.Boolean(), nullable=False),
    sa.Column('members_can_edit_group_info', sa.Boolean(), nullable=False),
    sa.Column('admin_only_messaging', sa.Boolean(), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_direct_key'), 'conversations', ['direct_key'], unique=True)
    op.create_index(op.f('ix_conversations_last_message_at'), 'conversations', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_conversations_type'), 'conversations', ['type'], unique=False)
    op.create_index('ix_conversations_updated', 'conversations', ['updated_at'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=191), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DELETED', name='userstatus', native_enum=False, length=16), nullable=False),
    sa.Column('streak_notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('streak_reminders_enabled', sa.Boolean(), nullable=False),
    sa.Column('streak_freezes_enabled', sa.Boolean(), nullable=False),
    sa.Column('streak_visible', sa.Boolean(), nullable=False),
    sa.Column('read_receipts_enabled', sa.Boolean(), nullable=False),
    sa.Column('show_online_status', sa.Boolean(), nullable=False),
    sa.Column('profile_visibility', sa.String(length=16), nullable=False),
    sa.Column('notification_preview_allowed', sa.Boolean(), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('theme', sa.String(length=16), nullable=False),
    sa.Column('timezone', sa.String(length=32), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reset_token_hash', sa.String(length=128), nullable=True),
    sa.Column('reset_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_code_hash', sa.String(length=128), nullable=True),
    sa.Column('verification_code_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index('ix_users_status_last_seen', 'users', ['status', 'last_seen_at'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('blocked_users',
    sa.Column('user_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('blocked_user_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['blocked_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_blocked_pair', 'blocked_users', ['user_id', 'blocked_user_id'], unique=True)
    op.create_index(op.f('ix_blocked_users_blocked_user_id'), 'blocked_users', ['blocked_user_id'], unique=False)
    op.create_index(op.f('ix_blocked_users_user_id'), 'blocked_users', ['user_id'], unique=False)
    op.create_table('calls',
    sa.Column('conversation_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('initiator_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('kind', sa.Enum('VOICE', 'VIDEO', name='callkind', native_enum=False, length=16), nullable=False),
    sa.Column('direction', sa.Enum('INCOMING', 'OUTGOING', name='calldirection', native_enum=False, length=16), nullable=False),
    sa.Column('state', sa.Enum('RINGING', 'CONNECTING', 'ACTIVE', 'ENDED', 'MISSED', 'REJECTED', 'CANCELED', name='callstate', native_enum=False, length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('peer_user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calls_conversation_id'), 'calls', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_calls_initiator_id'), 'calls', ['initiator_id'], unique=False)
    op.create_index(op.f('ix_calls_peer_user_id'), 'calls', ['peer_user_id'], unique=False)
    op.create_index(op.f('ix_calls_state'), 'calls', ['state'], unique=False)
    op.create_index('ix_calls_user_history', 'calls', ['initiator_id', 'created_at'], unique=False)
    op.create_table('devices',
    sa.Column('user_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('platform', sa.Enum('IOS', name='deviceplatform', native_enum=False, length=16), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=False),
    sa.Column('os_version', sa.String(length=64), nullable=True),
    sa.Column('app_version', sa.String(length=32), nullable=True),
    sa.Column('push_token', sa.String(length=512), nullable=True),
    sa.Column('refresh_token_hash', sa.String(length=128), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_table('friend_requests',
    sa.Column('sender_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('recipient_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'REMOVED', 'BLOCKED', name='friendshipstatus', native_enum=False, length=16), nullable=False),
    sa.Column('message', sa.String(length=280), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_friend_requests_pair', 'friend_requests', ['sender_id', 'recipient_id'], unique=True)
    op.create_index(op.f('ix_friend_requests_recipient_id'), 'friend_requests', ['recipient_id'], unique=False)
    op.create_index('ix_friend_requests_recipient_status', 'friend_requests', ['recipient_id', 'status'], unique=False)
    op.create_index(op.f('ix_friend_requests_sender_id'), 'friend_requests', ['sender_id'], unique=False)
    op.create_table('friendships',
    sa.Column('user_a', mysql.CHAR(length=32), nullable=False),
    sa.Column('user_b', mysql.CHAR(length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'REMOVED', 'BLOCKED', name='friendshipstatus', native_enum=False, length=16), nullable=False),
    sa.Column('removed_by', mysql.CHAR(length=32), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['removed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_a'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_b'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_friendships_pair', 'friendships', ['user_a', 'user_b'], unique=True)
    op.create_index('ix_friendships_status', 'friendships', ['status'], unique=False)
    op.create_index(op.f('ix_friendships_user_a'), 'friendships', ['user_a'], unique=False)
    op.create_index(op.f('ix_friendships_user_b'), 'friendships', ['user_b'], unique=False)
    op.create_table('messages',
    sa.Column('server_id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('sender_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('kind', sa.Enum('TEXT', 'EMOJI', 'STICKER', 'GIF', 'IMAGE', 'VIDEO', 'FILE', 'VOICE', 'CONTACT', 'LOCATION', 'SYSTEM', name='messagekind', native_enum=False, length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('reply_to_message_id', mysql.CHAR(length=32), nullable=True),
    sa.Column('client_sequence', sa.BigInteger(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to_message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'server_id', name='uq_message_conv_server')
    )
    op.create_index('ix_messages_conv_server', 'messages', ['conversation_id', 'server_id'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_index('ix_messages_sender_seq', 'messages', ['sender_id', 'client_sequence'], unique=False)
    op.create_index(op.f('ix_messages_sent_at'), 'messages', ['sent_at'], unique=False)
    op.create_index(op.f('ix_messages_server_id'), 'messages', ['server_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('user_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('messages_enabled', sa.Boolean(), nullable=False),
    sa.Column('groups_enabled', sa.Boolean(), nullable=False),
    sa.Column('calls_enabled', sa.Boolean(), nullable=False),
    sa.Column('streak_notifications', sa.Boolean(), nullable=False),
    sa.Column('streak_reminders', sa.Boolean(), nullable=False),
    sa.Column('friend_requests', sa.Boolean(), nullable=False),
    sa.Column('security_alerts', sa.Boolean(), nullable=False),
    sa.Column('show_preview', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start', sa.String(length=5), nullable=True),
    sa.Column('quiet_hours_end', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('notifications',
    sa.Column('user_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('kind', sa.Enum('MESSAGE', 'GROUP_MESSAGE', 'FRIEND_REQUEST', 'FRIEND_ACCEPTED', 'CALL', 'STREAK', 'STREAK_MILESTONE', 'STREAK_REMINDER', 'SECURITY', 'SYSTEM', name='notificationkind', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_via_apns', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_kind'), 'notifications', ['kind'], unique=False)
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('streak_day_qualifications',
    sa.Column('user_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('peer_user_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('conversation_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('first_message_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['peer_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'conversation_id', 'day', name='uq_qualification_ucd')
    )
    op.create_index('ix_qualification_day', 'streak_day_qualifications', ['day'], unique=False)
    op.create_index('ix_qualification_peer_day', 'streak_day_qualifications', ['peer_user_id', 'day'], unique=False)
    op.create_index(op.f('ix_streak_day_qualifications_conversation_id'), 'streak_day_qualifications', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_streak_day_qualifications_peer_user_id'), 'streak_day_qualifications', ['peer_user_id'], unique=False)
    op.create_index(op.f('ix_streak_day_qualifications_user_id'), 'streak_day_qualifications', ['user_id'], unique=False)
    op.create_table('streak_events',
    sa.Column('user_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('peer_user_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('conversation_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=24), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('streak_after', sa.Integer(), nullable=False),
    sa.Column('meta', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['peer_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streak_events_conversation_id'), 'streak_events', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_streak_events_day'), 'streak_events', ['day'], unique=False)
    op.create_index(op.f('ix_streak_events_peer_user_id'), 'streak_events', ['peer_user_id'], unique=False)
    op.create_index('ix_streak_events_user_day', 'streak_events', ['user_id', 'day'], unique=False)
    op.create_index(op.f('ix_streak_events_user_id'), 'streak_events', ['user_id'], unique=False)
    op.create_table('streaks',
    sa.Column('user_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('peer_user_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('conversation_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('longest_start_date', sa.Date(), nullable=True),
    sa.Column('prepared_at', sa.Date(), nullable=True),
    sa.Column('freezes_available', sa.Integer(), nullable=False),
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['peer_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'peer_user_id', 'conversation_id', name='uq_streak_triple')
    )
    op.create_index('ix_streak_user_alive', 'streaks', ['user_id', 'prepared_at'], unique=False)
    op.create_index(op.f('ix_streaks_conversation_id'), 'streaks', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_streaks_peer_user_id'), 'streaks', ['peer_user_id'], unique=False)
    op.create_index(op.f('ix_streaks_user_id'), 'streaks', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=32), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('avatar_thumb_url', sa.String(length=512), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_region', sa.String(length=8), nullable=True),
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('call_participants',
    sa.Column('call_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_participants_call_id'), 'call_participants', ['call_id'], unique=False)
    op.create_index('ix_call_participants_user', 'call_participants', ['user_id'], unique=False)
    op.create_index(op.f('ix_call_participants_user_id'), 'call_participants', ['user_id'], unique=False)
    op.create_table('conversation_members',
    sa.Column('conversation_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='memberrole', native_enum=False, length=16), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_muted', sa.Boolean(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('last_read_message_id', mysql.CHAR(length=32), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('nickname', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_read_message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'user_id', name='uq_member_conversation_user')
    )
    op.create_index(op.f('ix_conversation_members_conversation_id'), 'conversation_members', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_members_user_id'), 'conversation_members', ['user_id'], unique=False)
    op.create_index('ix_members_user', 'conversation_members', ['user_id'], unique=False)
    op.create_table('message_attachments',
    sa.Column('message_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('thumb_url', sa.String(length=512), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('waveform', sa.JSON(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_attachments_message_id'), 'message_attachments', ['message_id'], unique=False)
    op.create_table('message_deletions',
    sa.Column('message_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('deleted_by', mysql.CHAR(length=32), nullable=False),
    sa.Column('delete_for', sa.String(length=16), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_deletions_message_id'), 'message_deletions', ['message_id'], unique=False)
    op.create_table('message_edits',
    sa.Column('message_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('editor_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('previous_body', sa.Text(), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['editor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_edits_message_id'), 'message_edits', ['message_id'], unique=False)
    op.create_table('message_reactions',
    sa.Column('message_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('emoji', sa.String(length=16), nullable=False),
    sa.Column('reaction_type', sa.Enum('LIKE', 'LOVE', 'LAUGH', 'WOW', 'SAD', 'ANGRY', 'CUSTOM', name='reactiontype', native_enum=False, length=16), nullable=False),
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', 'emoji', name='uq_reaction_message_user_emoji')
    )
    op.create_index(op.f('ix_message_reactions_message_id'), 'message_reactions', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_reactions_user_id'), 'message_reactions', ['user_id'], unique=False)
    op.create_table('message_receipts',
    sa.Column('message_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('conversation_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_receipt_message_user')
    )
    op.create_index(op.f('ix_message_receipts_conversation_id'), 'message_receipts', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_message_receipts_message_id'), 'message_receipts', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_receipts_user_id'), 'message_receipts', ['user_id'], unique=False)
    op.create_index('ix_receipts_conversation_user', 'message_receipts', ['conversation_id', 'user_id', 'read_at'], unique=False)
    op.create_table('reports',
    sa.Column('reporter_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('kind', sa.Enum('USER', 'MESSAGE', 'CONVERSATION', name='reportkind', native_enum=False, length=16), nullable=False),
    sa.Column('target_user_id', mysql.CHAR(length=32), nullable=True),
    sa.Column('message_id', mysql.CHAR(length=32), nullable=True),
    sa.Column('conversation_id', mysql.CHAR(length=32), nullable=True),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'REVIEWING', 'RESOLVED', 'DISMISSED', name='reportstatus', native_enum=False, length=16), nullable=False),
    sa.Column('resolved_by', mysql.CHAR(length=32), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('moderation_note', sa.Text(), nullable=True),
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_conversation_id'), 'reports', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_reports_kind'), 'reports', ['kind'], unique=False)
    op.create_index(op.f('ix_reports_message_id'), 'reports', ['message_id'], unique=False)
    op.create_index(op.f('ix_reports_reporter_id'), 'reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_index(op.f('ix_reports_target_user_id'), 'reports', ['target_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_target_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_reporter_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_message_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_kind'), table_name='reports')
    op.drop_index(op.f('ix_reports_conversation_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_receipts_conversation_user', table_name='message_receipts')
    op.drop_index(op.f('ix_message_receipts_user_id'), table_name='message_receipts')
    op.drop_index(op.f('ix_message_receipts_message_id'), table_name='message_receipts')
    op.drop_index(op.f('ix_message_receipts_conversation_id'), table_name='message_receipts')
    op.drop_table('message_receipts')
    op.drop_index(op.f('ix_message_reactions_user_id'), table_name='message_reactions')
    op.drop_index(op.f('ix_message_reactions_message_id'), table_name='message_reactions')
    op.drop_table('message_reactions')
    op.drop_index(op.f('ix_message_edits_message_id'), table_name='message_edits')
    op.drop_table('message_edits')
    op.drop_index(op.f('ix_message_deletions_message_id'), table_name='message_deletions')
    op.drop_table('message_deletions')
    op.drop_index(op.f('ix_message_attachments_message_id'), table_name='message_attachments')
    op.drop_table('message_attachments')
    op.drop_index('ix_members_user', table_name='conversation_members')
    op.drop_index(op.f('ix_conversation_members_user_id'), table_name='conversation_members')
    op.drop_index(op.f('ix_conversation_members_conversation_id'), table_name='conversation_members')
    op.drop_table('conversation_members')
    op.drop_index(op.f('ix_call_participants_user_id'), table_name='call_participants')
    op.drop_index('ix_call_participants_user', table_name='call_participants')
    op.drop_index(op.f('ix_call_participants_call_id'), table_name='call_participants')
    op.drop_table('call_participants')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_streaks_user_id'), table_name='streaks')
    op.drop_index(op.f('ix_streaks_peer_user_id'), table_name='streaks')
    op.drop_index(op.f('ix_streaks_conversation_id'), table_name='streaks')
    op.drop_index('ix_streak_user_alive', table_name='streaks')
    op.drop_table('streaks')
    op.drop_index(op.f('ix_streak_events_user_id'), table_name='streak_events')
    op.drop_index('ix_streak_events_user_day', table_name='streak_events')
    op.drop_index(op.f('ix_streak_events_peer_user_id'), table_name='streak_events')
    op.drop_index(op.f('ix_streak_events_day'), table_name='streak_events')
    op.drop_index(op.f('ix_streak_events_conversation_id'), table_name='streak_events')
    op.drop_table('streak_events')
    op.drop_index(op.f('ix_streak_day_qualifications_user_id'), table_name='streak_day_qualifications')
    op.drop_index(op.f('ix_streak_day_qualifications_peer_user_id'), table_name='streak_day_qualifications')
    op.drop_index(op.f('ix_streak_day_qualifications_conversation_id'), table_name='streak_day_qualifications')
    op.drop_index('ix_qualification_peer_day', table_name='streak_day_qualifications')
    op.drop_index('ix_qualification_day', table_name='streak_day_qualifications')
    op.drop_table('streak_day_qualifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_kind'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_messages_server_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_sent_at'), table_name='messages')
    op.drop_index('ix_messages_sender_seq', table_name='messages')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index('ix_messages_conv_server', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_friendships_user_b'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_user_a'), table_name='friendships')
    op.drop_index('ix_friendships_status', table_name='friendships')
    op.drop_index('ix_friendships_pair', table_name='friendships')
    op.drop_table('friendships')
    op.drop_index(op.f('ix_friend_requests_sender_id'), table_name='friend_requests')
    op.drop_index('ix_friend_requests_recipient_status', table_name='friend_requests')
    op.drop_index(op.f('ix_friend_requests_recipient_id'), table_name='friend_requests')
    op.drop_index('ix_friend_requests_pair', table_name='friend_requests')
    op.drop_table('friend_requests')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index('ix_calls_user_history', table_name='calls')
    op.drop_index(op.f('ix_calls_state'), table_name='calls')
    op.drop_index(op.f('ix_calls_peer_user_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_initiator_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_conversation_id'), table_name='calls')
    op.drop_table('calls')
    op.drop_index(op.f('ix_blocked_users_user_id'), table_name='blocked_users')
    op.drop_index(op.f('ix_blocked_users_blocked_user_id'), table_name='blocked_users')
    op.drop_index('ix_blocked_pair', table_name='blocked_users')
    op.drop_table('blocked_users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index('ix_users_status_last_seen', table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_conversations_updated', table_name='conversations')
    op.drop_index(op.f('ix_conversations_type'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_last_message_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_direct_key'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
